---
model_name: dream5
score_name: "auroc" # "auroc" or "aupr" or "auroc_p_value" or "aupr_p_value" or "score" or "score_aupr"
verbosity: "progress_bars" # "log" or "progress_bars" or "suppressed"
parallel_mode: "multiprocessing" # "multiprocessing" or "threading"
parallel_jobs: 8
trunk_size: 100 # Regulate the memory usage
alpha_log2_values:
  start: -6
  stop: 6
  num: 17
beta_log2_values:
  start: -6
  stop: 6
  num: 17
skip_existing_preds: true
max_level: -1
data_root: "data/"
model:
  goldstandards_folder: "goldstandards/"
  datasets_folder: "datasets/"
  predictions_folder: "predictions/"
  results_folder: "results/"
  p_values_folder: "p_values/"
  has_p_values: false
  has_self_loops: false
  evaluator: Evaluator
learner_params:
  n_trees: 100
  max_features: sqrt
