---
model_name: ecoli_subnetworks
score_name: score_aupr
alpha_log2_values:
  start: -6
  stop: 6
  num: 17
beta_log2_values:
  start: -6
  stop: 6
  num: 17
skip_existing_preds: true
max_level: -1
data_root: data
model:
  goldstandards_folder: goldstandards
  datasets_folder: datasets
  predictions_folder: predictions
  results_folder: results
  p_values_folder: p_values
  has_p_values: false
  has_self_loops: false
  evaluator: Evaluator
learner_params:
  n_trees: 100
  max_features: sqrt
  trunk_size: 100
  parallel_jobs: 8
